# -*- coding: utf-8 -*-
"""SuperCalcAPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EqPpEtupWsW76oPKTzxibGWtqgOj1d2
"""

!pip install selenium

!apt-get update
!apt-get install -y chromium-browser

!apt install chromium-chromedriver

from selenium import webdriver
import time

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.chrome.service import Service

service = Service()

options = webdriver.ChromeOptions()

driver = webdriver.Chrome(service=service, options=options)

# !pip install --upgrade selenium
# !apt-get update
# !apt install chromium-chromedriver

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

# Set the path to the ChromeDriver executable
# Replace '/path/to/chromedriver' with the actual path on your system
service = Service(executable_path='/usr/bin/chromedriver')

# Configure Chrome options if needed
options = Options()

# Initialize the ChromeDriver
driver = webdriver.Chrome(service=service, options=options)

driver.get("https://egestorab.saude.gov.br/gestaoaps/relFinanciamentoParcela.xhtml")

# Define a dictionary to store element IDs and data
campos = {
    "j_idt58:uf": "PE",
    "j_idt58:municipio": "RIBEIRÃO",
    "j_idt58:ano": "2024",
    "j_idt58:compInicio": "ABR/2024",
    "j_idt58:compFim": "ABR/2024",
}

# Loop through the dictionary to find and fill elements
for element_id, value in campos.items():
    element = driver.find_element(By.ID, element_id)
    element.send_keys(value)
    time.sleep(1)

element = driver.find_element(By.ID, "j_idt58:verResultado")
element.click()

!cd..
!ls